# Generated by Django 5.1.3 on 2024-12-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('character_class', models.CharField(choices=[('Warlock', 'Warlock'), ('Paladin', 'Paladin'), ('Shaman', 'Shaman'), ('Mage', 'Mage'), ('Druid', 'Druid'), ('Warrior', 'Warrior')], max_length=20)),
                ('position', models.CharField(choices=[('Tank', 'Tank'), ('Heal', 'Heal'), ('Melee_Dps', 'Melee DPS'), ('Ranged_Dps', 'Ranged DPS')], max_length=20)),
            ],
        ),
    ]
